[package]
name = "log_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
log = { path = "../log" }
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
lazy_static = "1.4.0"
constructor = "*"
inventory = "*"
